language: php

matrix:
  include:
    - php: 5.5
      env: COLLECT_COVERAGE=true
    - php: 5.6
      env: COLLECT_COVERAGE=true
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: 7.0
  fast_finish: true

install:
  - travis_retry composer install

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - if [ "$COLLECT_COVERAGE" == "true" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
